package com.SecKillProject.dao;

import com.SecKillProject.dataobject.UserDataObject;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Component;

@Component
public interface UserDataObjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Fri Jul 05 15:17:08 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Fri Jul 05 15:17:08 CST 2019
     */
    int insert(UserDataObject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Fri Jul 05 15:17:08 CST 2019
     */
    int insertSelective(UserDataObject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Fri Jul 05 15:17:08 CST 2019
     */
    UserDataObject selectByPrimaryKey(Integer id);

    UserDataObject selectByTelephone(String telephone);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Fri Jul 05 15:17:08 CST 2019
     */
    int updateByPrimaryKeySelective(UserDataObject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Fri Jul 05 15:17:08 CST 2019
     */
    int updateByPrimaryKey(UserDataObject record);
}