package com.SecKillProject.dao;

import com.SecKillProject.dataobject.UserPwdDataObject;
import org.springframework.stereotype.Component;

@Component
public interface UserPwdDataObjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Fri Jul 05 15:17:08 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Fri Jul 05 15:17:08 CST 2019
     */
    int insert(UserPwdDataObject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Fri Jul 05 15:17:08 CST 2019
     */
    int insertSelective(UserPwdDataObject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Fri Jul 05 15:17:08 CST 2019
     */
    UserPwdDataObject selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Fri Jul 05 15:17:08 CST 2019
     */
    UserPwdDataObject selectByUserId(Integer userID);

    int updateByPrimaryKeySelective(UserPwdDataObject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Fri Jul 05 15:17:08 CST 2019
     */
    int updateByPrimaryKey(UserPwdDataObject record);
}